baseURL = "http://oche.ninja/subproject68/"


languageCode = "en-us"
title = "Subproject 68"
theme = "tale"
summaryLength = 60

[params]
  author = "Sutki KynyR"
  description = "Rants!"


[[menu.main]]
      name = "About"
      weight = 1
      url = "/about/"
      identifier = "about"
